# Generated by Django 4.1.7 on 2023-03-27 14:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="quantity",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
