# Generated by Django 4.1.7 on 2023-03-28 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("categories", "0004_alter_category_name"),
        ("products", "0003_alter_product_quantity"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={"ordering": ("name",)},
        ),
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="categories.category",
            ),
        ),
    ]
