# Generated by Django 4.1.7 on 2023-03-27 15:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "orders",
            "0002_order_tracking_no_orderitem_price_alter_order_status_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="shipping_method",
        ),
    ]
