# Generated by Django 4.1.7 on 2023-03-28 09:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0003_remove_order_shipping_method"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="order",
            options={"ordering": ("-created_on",)},
        ),
    ]
