# Generated by Django 4.1.7 on 2023-03-27 16:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("categories", "0002_alter_category_name"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name": "Category", "verbose_name_plural": "Categories"},
        ),
    ]
