# Generated by Django 4.1.7 on 2023-03-27 16:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("categories", "0003_alter_category_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(
                choices=[
                    ("automobiles", "Automobiles"),
                    ("electronics", "Electronics"),
                    ("fashion", "Fashion"),
                    ("food and beverages", "Food and Beverages"),
                    ("furnitures and decor", "Furnitures and Decor"),
                    ("mobile phones", "Mobile Phones"),
                    ("toys", "Toys"),
                ],
                max_length=255,
                unique=True,
            ),
        ),
    ]
