# Generated by Django 4.1.7 on 2023-03-31 19:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("carts", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cartitem",
            name="quantity",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
