# Generated by Django 5.1.2 on 2024-10-18 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0003_alter_cartitem_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='created_on',
            new_name='date_created',
        ),
        migrations.RenameField(
            model_name='cart',
            old_name='updated_on',
            new_name='date_modified',
        ),
        migrations.RenameField(
            model_name='cartitem',
            old_name='created_on',
            new_name='date_created',
        ),
        migrations.RenameField(
            model_name='cartitem',
            old_name='updated_on',
            new_name='date_modified',
        ),
    ]
