# Generated by Django 4.1.7 on 2023-03-31 17:52

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("automobiles", "Automobiles"),
                            ("electronics", "Electronics"),
                            ("fashion", "Fashion"),
                            ("food and beverages", "Food and Beverages"),
                            ("furnitures and decor", "Furnitures and Decor"),
                            ("mobile phones", "Mobile Phones"),
                            ("toys", "Toys"),
                        ],
                        max_length=255,
                        unique=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "Category",
                "verbose_name_plural": "Categories",
            },
        ),
    ]
