# Generated by Django 5.1.2 on 2024-10-18 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'ordering': ('-date_created',), 'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='created_on',
            new_name='date_created',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='updated_on',
            new_name='date_modified',
        ),
    ]
