# Generated by Django 4.1.7 on 2023-03-28 17:17

import apps.users.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_alter_customuser_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="phone_no",
            field=models.CharField(
                max_length=11, validators=[apps.users.models.validated_phone_no]
            ),
        ),
    ]
